### ISSUE TITLE
Contact page KO : The captcha problem

### ISSUE THREAD

**Issue by GoulvenF** [open4good/open4goods-light#315]
[Version française (google translate)]()

### Problem

- The contact page is KO, because of googleRecCaptcha changes, domain neet to be validated again 
- BUT google reCaptcha is not a GDPR compliant solution

### Solution

- Remove google reCaptcha and implement [hCaptcha](https://www.hcaptcha.com/plans)
- Need to be implemented on Contact page and controller, on feedback page and controller

### Requisites

-  must be a generic and well documented mechanism, to be able to use it easily in new controlers / endpoints that must be bot protected. 

### Tips /  work tracks

- technical docs : https://docs.hcaptcha.com/
- could be a new, separate spring boot starter project ?

**Comment by Ashwinn11** [comment]
waiting for review

**Comment by GoulvenF** [comment]
Hi Ashwinn11,

Sorry for the late answer, and thank you for your contribution. This is working great !
