### ISSUE TITLE
Bug au moment de l'envoie du formulaires de contact

### ISSUE THREAD

**Issue by rcondamin** [open4good/open4goods-light#44]
Erreur ! Nous n'avons pas pu envoyer votre message, en raison d'une erreur technique ! (Le mail n'a pas pu être envoyé : Authentication failed; nested exception is javax.mail.AuthenticationFailedException: 535-5.7.8 Username and Password not accepted. Learn more at 535 5.7.8 https://support.google.com/mail/?p=BadCredentials ba5-20020a0560001c0500b0021d6c7a9f50sm1075190wrb.41 - gsmtp ) !
 
 Merci

Raphael, du site www.shopetic.com

**Comment by GoulvenF** [comment]
Merci, et désolé pour le retard. C'est réparé.

Bien votre site shopetic !
